### ISSUE TITLE
Clarifying Questions for Project Description

### ISSUE THREAD

**Issue by agoz17** [bounswe/bounswe2017group7#21]
After the meeting we had February 24th. We have some vital questions about the scope and efficiency of our project.

**1-** The most important issue for us is the practicality of the software we are going to develop. Our software is going to be a chatbot which will have a conversation with its users and interact with them about the books. When we try to visualize and create mock-up scenarios, we realised that this software has some fundamental problems such as;

We have very little space to show books and their descriptions via chat app interface. In addition to that it is much more hard to read and long messages through some chat app since its whole purpose is on communicating through rather short messages. 

If a user wants to see some books from a genre, firstly we can only send some name list of the books, we can’t send description for all of the books to not spam the users. 

When we think about a scenario that a user wants a book to read in history genre, first we list 10 books, then user requests each book’s description until he/she finds interesting one. This procedure much faster and easier in the book e-stores. 

When we consider with just one click we can choose genre, sorting feature, price in these websites. We can see the ratings, small description, cover photo, price in the same block of page. If we want we can reach much more detailed page in a well organized way.

Since we don’t have the chance of creating a page scheme we want in the Telegram interface, it is going to be much more hard to take attentions of the users.
It can be perceived as the terminal(command-line) of book advertising by the end user because of these problems.

We have great disadvantages compared to book e-stores. We have practicality issues for average user. We have method and purpose mismatch considering only chatting infrastructre is not really fit for long and detailed book search.

What we can offer to this problem is to support chatting with our self designed pages and features. But in this case we can’t use the Telegram framework. This is the customer’s call.

**2-** For the profile pages, we concluded that they are going to be content provider as it happens in the wikipedia. However we had requests towards profiles should be visible to each other. The question is are users going to be only content provider without any profile pages, or are they going to be visible to each other with their own profile pages and comments?

The same question arises here, if we are going to use Telegram chatbot tool, we need to use Telegram user names for this purpose or we can create a completely distinct website has these profiles as part of this software but it would be very impractical and complex design. What is the right solution here?

**Comment by ardax** [comment]
Dear Group 7,

1- I hear your concerns. I wish you come to this conclusion earlier so that we could have met and discussed the matter face-to-face. Please note that it is not required to give/show all information that we used to see in web pages through your interface. Instead of showing top 10 results, maybe you need to show the best result or two. For example, it is not feasible to show all description about a book but you may show first couple of sentences from the description. Keep sentences short, for example say "wanna see ... ?" instead of "would you like to see ...?" You need to come up with such methods. Of course you are not expected to provide all the comfort of a website. Despite those disadvantages, chatbot interface will provide other advantages, like more customized and assistive interaction. Keep in mind that in this case you are designing conversations, not web pages. It is completely new paradigm. If you can share your mockups, I might comment on them and try to understand these situations with you.

Let me share my three possible solutions here. First, Telegram has also desktop and web browser interfaces. Those may provide larger screens so you can show more content, even though you may still not able to show structured content as you desire. However, it would be ideal to stick with the mobile interface. Second solution is to design your own interface and use Telegram API to connect the user to the Telegram environment. There is "User Authorization" section in the API so I suppose you can still use the API for the user's side. You can design special interface to show details about a book. You may consider building your own client-server structure but that may be costly in terms of time. Thirdly, Facebook Messenger's chatbot environment has visual panels called Templates to list things in a visually friendly manner. If they suit your needs, you may consider switching to Messenger API. All in all, I encourage you to stick with the mobile Telegram interface, if possible. 


2- Users will have a basic profile. However, since you don't have large places or visualization tools at your disposal in a chat environment, user profiles will have a different shape. You may list most recently high-rated book to tell about a user or book labels she used to express her interest area. Or you may compare two users' interested books and realized that they both like the same book, tell that. Note that these are couple of things you can tell about a user. Like you use chat to find books, you can also chat to learn about a user as well. That means, instead of showing a profile page with all possible information about user, user should be able to ask about other users, such as "which books did she like?" or "what are her interest areas?" or chatbot drives the chat by saying "wanna see the book she liked recently?"


Please comment more, so we can discuss further. I will be at the department this weekend. You may reach me at my office as well.

Believe it or not, I am also happy. Because this is something very new to you. You brainstormed on this topic and came up with this conclusion. Even though result seems not fruitful (yet), it made you "think differently". I hope you put more energy and brainpower into this and come up with a sufficient solution. As I said before, I am always here to help, just ask!

**Comment by theTytoAlba** [comment]
Closing this issue since we had several face-to-face meetings considering the issues mentioned here. First mock-ups were added. The admin web mockups will be updated while the telegram user mockups will mostly stay the same as they fit the lastest description our customer described.
