### ISSUE TITLE
Update the Requirements

### ISSUE THREAD

**Issue by theTytoAlba** [bounswe/bounswe2017group7#66]
We have talked to our new customer Onur and he suggested some changes to our existing requirements. We should update the requirements according to these changes.

**Comment by agoz17** [comment]
We had meeting to update our requirements as Irmak said. We have updated our requirements and also our plan according to these changes. Since our initial plan was not meeting our needs in terms of time allocations to each task, we need to rearrange this time allocations. Salih is going to help us to resolve this issue with our template new plan. @sevgicansalih
